- action:
    data:
      event: Home Assistant has Started
      value1: Home Assistant has Started
    service: ifttt.trigger
  alias: Home Assistant has Started
  condition: []
  id: '1507941187276'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      event: Home Assistant Restarted
      value1: Home Assistant Restarted
    service: ifttt.trigger
  alias: Home Assistant Restarted
  condition: []
  id: '1507941691616'
  trigger:
  - event: shutdown
    platform: homeassistant
- id: '1508871600249'
  alias: Warehouse Flood Alert IFTTT
  trigger:
  - entity_id: binary_sensor.neo_coolcam_water_leakage_detector_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: Flood Alert
      value1: Flood Alert
    service: ifttt.trigger
- action:
  - data:
      event: Warehouse Flood Alert
      value1: Warehouse Flood Alert
    service: ifttt.trigger
  alias: Warehouse Flood Alert email
  condition: []
  id: '1508875982323'
  trigger:
  - entity_id: binary_sensor.neo_coolcam_water_leakage_detector_sensor
    from: 'off'
    platform: state
    to: 'on'
- id: '1510527510471'
  alias: Cabinet Light On
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001a1f88b
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.cabinet
    service: light.turn_on
- action:
  - data:
      entity_id: light.cabinet
    service: light.turn_off
  alias: Cabinet Light Off
  condition: []
  id: '1510528193692'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001a1f88b
    from: 'on'
    platform: state
    to: 'off'
- id: '1511488400509'
  alias: Wake Me Up - Working Days
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state
      }}'
  condition:
  - condition: state
    entity_id: input_boolean.alarmweekday
    state: 'on'
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch, light.natali_bed_light,
        light.office_fan_light, light.master_bedroom_light, light.lians_fan_and_light_s1
    service: light.turn_on
- id: '1511488762409'
  alias: Wake Me Up - All Week Days
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state
      }}'
  condition:
  - condition: state
    entity_id: input_boolean.alarmweekday
    state: 'off'
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch
    service: light.turn_on
- id: '1511421769569'
  alias: Automation Night Mode Theme
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data:
      name: Midnight
    service: frontend.set_theme
- action:
  - data:
      name: default
    service: frontend.set_theme
  alias: Automation Day Mode Theme
  condition: []
  id: '1976531391659'
  trigger:
  - at: 06:00
    platform: time
- id: '1539107478361'
  alias: Hass_Harmony_PowerOff
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_poweroff
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: -1
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_watch_tv, input_boolean.remote_livingroom_harmony_movie_time,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- id: '1518769679421'
  alias: Hass_Harmony_Watch_TV
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_watch_tv
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: 35833943
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_movie_time,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- id: '1015213673543'
  alias: Hass_Harmony_Movie_Time
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_movie_time
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: 36963022
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- id: '1518769679871'
  alias: Hass_Harmony_Listen_to_Music
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_listen_to_music
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: 35834622
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- id: '1518782679202'
  alias: Hass_Harmony_Playstation_4
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_playstation4
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: 35834332
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_movie_time,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_watch_tv
    service: input_boolean.turn_off
- id: '1015213674572'
  alias: Remote_Harmony_PowerOff
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "PowerOff"}}'
  condition: []
  action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_watch_tv
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_listen_to_music,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
  alias: Remote_Harmony_Watch_TV
  condition: []
  id: '1518769678537'
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "Watch
      TV"}}'
- action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_movie_time
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
  alias: Remote_Harmony_Movie_Time
  condition: []
  id: '1015213640042'
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "Watch
      a Movie"}}'
- action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_listen_to_music
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
  alias: Remote_Harmony_Listen_to_Music
  condition: []
  id: '1015213677294'
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "Listen
      to Music"}}'
- action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_listen_to_music
    service: input_boolean.turn_off
  alias: Remote_Harmony_Playstation_4
  condition: []
  id: '1015213671234'
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "Play
      PS4"}}'
- action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch, switch.bar_light
    service: light.turn_on
  alias: Enter Home
  condition:
  - after: sunset
    condition: sun
  id: '1520187454154'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00016cf3b7
    from: 'off'
    platform: state
    to: 'on'
- id: good_night
  alias: Good Night
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d0001f9f3052
      click_type: long_click_press
    event_type: click
    platform: event
  action:
  - data:
      entity_id: light.bar_lights
    service: light.turn_off
- id: '1536982795485'
  alias: Lians Room Fan
  trigger:
  - entity_id: light.lians_light_s1
    platform: state
  action:
  - data_template:
      payload_template: "{% if states.fan.lians_ceiling_fan.state == 'off' %}\n  1\n\
        {% elif states.fan.lians_ceiling_fan.attributes.speed == 'low' %}\n  2\n{%\
        \ elif states.fan.lians_ceiling_fan.attributes.speed == 'medium' %}\n  3\n\
        {% elif states.fan.lians_ceiling_fan.attributes.speed == 'high' %}\n  off\n\
        {% endif %}\n"
      topic: cmnd/LiansFan/FanSpeed
    service: mqtt.publish
- id: '1537625758241'
  alias: Lian Room Light T1 Switch On
  trigger:
  - entity_id: light.lians_light_s2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.lians_fan_light
    service: light.turn_on
- id: '1098625758547'
  alias: Lian Room Light T1 Switch Off
  trigger:
  - entity_id: light.lians_light_s2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.lians_fan_light
    service: light.turn_off
- id: '1234625758694'
  alias: Start Cleaning Room
  trigger:
  - entity_id: input_select.vacuum_room
    from: Select Room
    platform: state
  action:
  - data_template:
      entity_id: "{% if is_state(\"input_select.vacuum_room\", \"Living Room\") %}\n\
        \  script.vacuum_living_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Dining Room\") %}\n  script.vacuum_dining_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Kitchen\") %}\n  script.vacuum_kitchen\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Hallway\") %}\n  script.vacuum_hallway\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"M_Bedroom\") %}\n  script.vacuum_m_bedroom\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Lians Room\") %}\n  script.vacuum_lians_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Orins Room\") %}\n  script.vacuum_orins_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Office\") %}\n  script.vacuum_office\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Bathroom\") %}\n  script.vacuum_bathroom           \n{% else %} {% endif\
        \ %}\n"
    service: script.turn_on
  - data_template:
      option: Select Input
    entity_id: input_select.vacuum_room
    service: input_select.select_option
  hide_entity: true
- id: '7656982795345'
  alias: Orins and Ela Room Fan
  trigger:
  - entity_id: light.orins_and_ela_light_s1
    platform: state
  action:
  - data: {}
    data_template:
      payload_template: "{% if states.fan.orins_ela_ceiling_fan.state == 'off' %}\n\
        \  1\n{% elif states.fan.orins_ela_ceiling_fan.attributes.speed == 'low' %}\n\
        \  2\n{% elif states.fan.orins_ela_ceiling_fan.attributes.speed == 'medium'\
        \ %}\n  3\n{% elif states.fan.orins_ela_ceiling_fan.attributes.speed == 'high'\
        \ %}\n  off\n{% endif %}\n"
      topic: cmnd/Orins/FanSpeed
    service: mqtt.publish
- id: '1537625758204'
  alias: Orins and Ela Room Light T1 Switch On
  trigger:
  - entity_id: light.orins_and_ela_light_s2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.orins_ela_fan_light
    service: light.turn_on
- id: '1098625754371'
  alias: Orins and Ela Room Light T1 Switch Off
  trigger:
  - entity_id: light.orins_and_ela_light_s2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.orins_ela_fan_light
    service: light.turn_off
- id: '1549189786588'
  alias: Turn All Automation At Startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - alias: ''
    data:
      entity_id: group.all_automations
    service: automation.turn_on
