- action:
    data:
      event: Home Assistant has Started
      value1: Home Assistant has Started
    service: ifttt.trigger
  alias: Home Assistant has Started
  condition: []
  id: '1507941187276'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      event: Home Assistant Restarted
      value1: Home Assistant Restarted
    service: ifttt.trigger
  alias: Home Assistant Restarted
  condition: []
  id: '1507941691616'
  trigger:
  - event: shutdown
    platform: homeassistant
- id: '1508871600249'
  alias: Warehouse Flood Alert IFTTT
  trigger:
  - entity_id: binary_sensor.neo_coolcam_water_leakage_detector_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: Flood Alert
      value1: Flood Alert
    service: ifttt.trigger
- action:
  - data:
      event: Warehouse Flood Alert
      value1: Warehouse Flood Alert
    service: ifttt.trigger
  alias: Warehouse Flood Alert email
  condition: []
  id: '1508875982323'
  trigger:
  - entity_id: binary_sensor.neo_coolcam_water_leakage_detector_sensor
    from: 'off'
    platform: state
    to: 'on'
- id: '1510527510471'
  alias: Cabinet Light On
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001a1f88b
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.cabinet
    service: light.turn_on
- action:
  - data:
      entity_id: light.cabinet
    service: light.turn_off
  alias: Cabinet Light Off
  condition: []
  id: '1510528193692'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001a1f88b
    from: 'on'
    platform: state
    to: 'off'
- id: '1539107478361'
  alias: Hass_Harmony_PowerOff
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_poweroff
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: -1
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_watch_tv, input_boolean.remote_livingroom_harmony_movie_time,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- id: '1518769679421'
  alias: Hass_Harmony_Watch_TV
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_watch_tv
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: 44060689
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_movie_time,
        input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
  - data: {}
    entity_id: script.fix_watch_tv_audio
    service: script.turn_on
- id: '1518782679202'
  alias: Hass_Harmony_Playstation_4
  trigger:
  - entity_id: input_boolean.remote_livingroom_harmony_playstation4
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      activity: 35834332
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv
    service: input_boolean.turn_off
- id: '1015213674572'
  alias: Remote_Harmony_PowerOff
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "PowerOff"}}'
  condition: []
  action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_listen_to_music, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
- action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_watch_tv
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_listen_to_music,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_off
  alias: Remote_Harmony_Watch_TV
  condition: []
  id: '1518769678537'
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "Watch
      TV"}}'
- action:
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_playstation4
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.remote_livingroom_harmony_poweroff, input_boolean.remote_livingroom_harmony_watch_tv,
        input_boolean.remote_livingroom_harmony_movie_time, input_boolean.remote_livingroom_harmony_listen_to_music
    service: input_boolean.turn_off
  alias: Remote_Harmony_Playstation_4
  condition: []
  id: '1015213671234'
  trigger:
  - platform: template
    value_template: '{{ states.remote.living_room.attributes.current_activity == "Play
      PS4"}}'
- id: '1234625758694'
  alias: Start Cleaning Room
  trigger:
  - entity_id: input_select.vacuum_room
    from: Select Room
    platform: state
  action:
  - data_template:
      entity_id: "{% if is_state(\"input_select.vacuum_room\", \"Living Room\") %}\n\
        \  script.vacuum_living_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Dining Room\") %}\n  script.vacuum_dining_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Kitchen\") %}\n  script.vacuum_kitchen\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Hallway\") %}\n  script.vacuum_hallway\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"M_Bedroom\") %}\n  script.vacuum_m_bedroom\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Lians Room\") %}\n  script.vacuum_lians_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Orins Room\") %}\n  script.vacuum_orins_room\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Office\") %}\n  script.vacuum_office\n{% elif is_state(\"input_select.vacuum_room\"\
        , \"Bathroom\") %}\n  script.vacuum_bathroom           \n{% else %} {% endif\
        \ %}\n"
    service: script.turn_on
  - data_template:
      option: Select Input
    entity_id: input_select.vacuum_room
    service: input_select.select_option
- id: '1549189786588'
  alias: Turn All Automation At Startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - alias: ''
    data:
      entity_id: group.all_automations
    service: automation.turn_on
- id: '1349189785702'
  alias: IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
- id: '1237189784130'
  alias: Toggle Lians Room Light on Long Click
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d0001f9f305
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      entity_id: light.lian_ifan_light
    entity_id: 'light.lian_ifan_light '
    service: light.toggle
- id: '4567189784130'
  alias: Toggle Lians Desk Lamp on Click
  description: Toggle Lians Desk Lamp on Click
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d0001f9f305
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      entity_id: switch.lians_desk_lamp
    entity_id: switch.lians_desk_lamp
    service: switch.toggle
- id: '1579189784245'
  alias: Toggle Orins Room Light on Long Click
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d000200792c
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      entity_id: light.orins_ifan_light
    entity_id: 'light.orins_ifan_light '
    service: light.toggle
- id: '3287189784290'
  alias: Toggle Orins Desk Lamp on Click
  description: Toggle Orins Desk Lamp on Click
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000200792c
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      entity_id: switch.orin_desk_lamp
    entity_id: switch.orin_desk_lamp
    service: switch.toggle
- id: '1562776630714'
  alias: AC turn on from Remote
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000395642c
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: climate.air_condition
    service: climate.turn_on
- id: '4502776630347'
  alias: AC turn off from Remote
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000395642c
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: climate.air_condition
    service: climate.turn_off
- id: '1563391755992'
  alias: Lians Room Sensor turn on light
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001a1f1ff
    for: 00:00:03
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d0001a1f1ff
    for: 00:00:03
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: '19:00'
      condition: time
  action:
  - data:
      entity_id: light.lian_ifan_light
    service: light.turn_on
- id: '5893391755123'
  alias: Lians Room Sensor turn off light after 10 Minutes
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001a1f1ff
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.lian_ifan_light
    service: light.turn_off
- id: '1568402493392'
  alias: Enter Home
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00016cf3b7
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: switch.fibaro_dining_room, switch.fibaro_kitchen_sink, switch.fibaro_kitchn_stove,
        switch.tkb_living_room
    service: switch.turn_on
- id: '8745983718345'
  alias: Master Bedroom Light On\Off on Fibaro Switch Toggle
  trigger:
  - entity_id: switch.fibaro_master_bedroom_2
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: switch.fibaro_master_bedroom_2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.lian_ifan_light
    entity_id: script.master_bedroom_fan_light
    service: script.toggle
- id: '1584904202350'
  alias: Gate Opened After Sunset
  description: ''
  trigger:
  - entity_id: binary_sensor.neo_coolcam_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.fibaro_garden_lights
    service: switch.turn_on
  - delay: 00:00:01
  - data:
      entity_id: switch.fibaro_front_porch_lights
    service: switch.turn_on
- id: '1585404441788'
  alias: Roof Fan Turn on If above 30 Degrees
  description: Roof Fan Turn on If above 30 Degrees
  trigger:
  - above: '30'
    entity_id: sensor.roof_fan_temperature
    for: '2'
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: switch.roof_fan
    entity_id: switch.roof_fan
    service: switch.turn_on
- id: '1585404510459'
  alias: Roof Fan Turn off If bellow 26 Degrees
  description: Roof Fan Turn off If bellow 26 Degrees
  trigger:
  - below: '27'
    entity_id: sensor.roof_fan_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: switch.roof_fan
    entity_id: switch.roof_fan
    service: switch.turn_off
- id: '1585996139760'
  alias: After HA Restart Turn On Roof Fan if above 30 Degrees
  description: After HA Restart Turn On Roof Fan if above 30 Degrees
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - above: '29'
    condition: numeric_state
    entity_id: sensor.roof_fan_temperature
  action:
  - data:
      entity_id: switch.roof_fan
    entity_id: switch.roof_fan
    service: switch.turn_on
- id: '1586268017390'
  alias: After HA Restart Turn Off Roof Fan if below 26 Degrees
  description: After HA Restart Turn Off Roof Fan if below 26 Degrees
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - below: '27'
    condition: numeric_state
    entity_id: sensor.roof_fan_temperature
  action:
  - data:
      entity_id: switch.roof_fan
    entity_id: switch.roof_fan
    service: switch.turn_off
- alias: Good Morning Alarm
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time_long.state
      }}'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.alarm_clock_status
        state: 'on'
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'on'
      - condition: time
        weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.alarm_clock_status
        state: 'on'
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'off'
  action:
    service: script.morning_music_alarm
  id: 6846a0b8e11d41eb878f92f5bc0891b1
- alias: Set Radio Volume
  trigger:
    platform: state
    entity_id: input_number.radio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: '{% if is_state("input_select.radio_speakers", "All Speakers") %}
        media_player.all_speakers {% elif is_state("input_select.radio_speakers",
        "Kitchen") %} media_player.kitchen {% elif is_state("input_select.radio_speakers",
        "Orins Room") %} media_player.orins_room {% elif is_state("input_select.radio_speakers",
        "Living Room") %} media_player.living_room {% elif is_state("input_select.radio_speakers",
        "Master Bedroom") %} media_player.master_bedroom {% elif is_state("input_select.radio_speakers",
        "Lians Room") %} media_player.lians_room {% elif is_state("input_select.radio_speakers",
        "Bathroom") %} media_player.bathroom {% elif is_state("input_select.radio_speakers",
        "Google Outdoor") %} media_player.bathroom            {% endif %}

        '
      volume_level: '{{  states.input_number.radio_volume.state  }}'
  id: 02415c16776140aa92d6a5e71fbe6bbb
- alias: Set Spotify Volume
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: '{% if is_state("input_select.spotify_source", "All Speakers") %}
        media_player.all_speakers  {% elif is_state("input_select.spotify_source",
        "Kitchen") %} media_player.kitchen  {% elif is_state("input_select.spotify_source",
        "Orins Room") %} media_player.orins_room  {% elif is_state("input_select.spotify_source",
        "Living Room") %} media_player.living_room {% elif is_state("input_select.spotify_source",
        "Master Bedroom") %} media_player.master_bedroom {% elif is_state("input_select.spotify_source",
        "Lians Room") %} media_player.lians_room {% elif is_state("input_select.spotify_source",
        "Google Outdoor") %} media_player.google_outdoor  {% elif is_state("input_select.spotify_source",
        "Bathroom") %} media_player.bathroom {% endif %}

        '
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
  id: 29cee2fd48464ee0a8f3ab8d200f7cfc
- id: '1591955654450'
  alias: Toggle Master Bedroom Light on Click
  description: Toggle Master Bedroom Light on Click
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000201afa6
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_master_bedroom_2
    entity_id: switch.fibaro_master_bedroom_2
    service: switch.toggle
- id: '1591959163992'
  alias: Toggle Master Bedroom Fan on Long Click
  description: Toggle Master Bedroom Fan on Long Click
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d000201afa6
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: script.master_bedroom_fan_off
    entity_id: script.master_bedroom_fan_off
    service: script.toggle
