
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: wallmount.yaml
      title: WallMount
      icon: mdi:television
      show_in_sidebar: true
      require_admin: true
  resources:
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module
  - url: /hacsfiles/group-card/group-card.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/lovelace-more-info-card/more-info-card.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /hacsfiles/lovelace-gap-card/gap-card.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: js    
  - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
    type: js    
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/swipe-card/swipe-card.js
    type: module    
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js    
  - url: /hacsfiles/light-popup-card/light-popup-card.js
    type: module
  - url: /hacsfiles/switch-popup-card/switch-popup-card.js
    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/thermostat-popup-card/thermostat-popup-card.js
    type: module
  - url: /hacsfiles/media_player-popup-card/media_player-popup-card.js
    type: module
  
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    url_path: zwave

browser_mod:

vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum Cleaner
    host: !secret vacuum_ip
    token: !secret vacuum_token

ifttt:
  key: !secret ifttt_key

mobile_app:

bond:
  host: !secret bond_ip 
  token: !secret bond_token 

frontend:
  javascript_version: latest
  themes: !include lovelace/configuration/themes.yaml 
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

remote:
  - platform: harmony
    name: Living Room
    host: !secret remote_host
    
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:blur
    url: !secret panel_iframe_url

stream:
ffmpeg:

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

smartir:
  update_branch: rc

light: !include lights.yaml
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
camera: !include cameras.yaml
media_player: !include media_players.yaml
fan: !include fans.yaml
climate: !include climate.yaml
switch: !include switches.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
