homeassistant:
  name: !secret homeassistant name
  temperature_unit: C
  latitude: !secret homeassistant latitude
  longitude: !secret homeassistant longitude
  elevation: 56
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

custom_updater:   # https://github.com/custom-components/custom_updater/wiki/Installation
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/custom-cards/tracker-card/master/tracker-card.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/matisaul/vertical-style-card/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
  
  show_installable: false  

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

zwave:
  usb_path: /dev/ttyACM0

vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum Cleaner
    host: !secret vacuum_ip
    token: !secret vacuum_token

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_aqara1_mac
      key: !secret xiaomi_aqara1_key
    - mac: !secret xiaomi_aqara2_mac
      key: !secret xiaomi_aqara2_key

owntracks:
  max_gps_accuracy: 200
  waypoints: True

ifttt:
  key: !secret ifttt_key

weather:
  - platform: darksky
    api_key: !secret weather_api_key

remote:
  - platform: harmony
    name: Living Room
    host: !secret remote_host

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-custom-fanspeed.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-fanspeed.html
  
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: pi
  password: !secret mqtt_password

lovelace:
  mode: yaml

config:
updater:
discovery:
conversation:
history:
logbook:
map:
system_health:
sun:
  
google_assistant:
  project_id: !secret google_assistant_project_id
  exposed_domains:
    - switch
    - light
    - group

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

light: !include includes/lights.yaml
zone: !include includes/zones.yaml  
group: !include includes/groups.yaml
automation: !include automations.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
camera: !include includes/cameras.yaml
media_player: !include includes/media_players.yaml
switch: !include includes/switches.yaml
binary_sensor: !include includes/binary_sensor.yaml
fan: !include includes/fans.yaml
climate: !include includes/climate.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
