automation:
  - id: '1235625754643'
    alias: yeeligt toggle
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001f9f305
        click_type: single
    action:
      service: light.toggle
      entity_id: light.lians_yeelight_rgb_light
    
input_boolean:
  rgb_dim:
    name: RGB traka Dim
    initial: off